#!/bin/bash

PROG=`echo $0 | rev | cut -d/ -f1 | rev`

function show_help {
  cat <<HELP
Usage:

  Create a new process
      $PROG -n[NAME] [ -v VERSION] [ -p PORT ]
                      or
      $PROG --new[=NAME ] [ --version VERSION ] [ --port PORT ]

  List running process
      $PROG -l[NAME]
            or
      $PROG --list[= NAME ]

  Show status of a process
      $PROG -s[NAME] [ -v VERSION ]
                 or
      $PROG --status[=NAME ] [ --version VERSION ]

  Start a stopped process
      $PROG --start[=NAME] [ --version VERSION]

  Stop a running process
      $PROG --stop[=NAME] [ --version VERSION]

  Remove a process
      $PROG --remove[=NAME] [ --version VERSION ]

  Restart a running process
      $PROG --restart[=NAME] [ --version VERSION ]

HELP
  # Define extra_option to add info extra for the options
  [ -n "$(type -t extra_option)" ] && ( extra_option )

cat <<HELP
Default values:

  NAME: $NAME
  PORT: $PORT
  VERSION: $VERSION
HELP

  # Define extra_default_value to add extra values
  [ -n "$(type -t extra_default_value)" ] && ( extra_default_value )

  echo -e "\nWorking with $DOCKERNAME docker image"

  # Define extra_help to add info extra at the end of the basic help
  [ -n "$(type -t extra_help)" ] && ( extra_help )

  echo -e "\nVersion: `cat $DOCKERWRAPPERS_ROOT/VERSION`"
}

if [ $# -eq 0 ] ; then
  show_help
  exit 0
fi

set -e

TEMP=`getopt -o n::s::r::l::v:p:c:h --long new::,status::,start::,stop::,restart::,remove::,list::,version:,port:,config:,help -n $PROG -- "$@"`
eval set -- "$TEMP"

function status_container {
  STATUS=`docker ps --filter name=$NAME-$VERSION --format {{.Status}}`
  if [ -n "$STATUS" ] ; then
    echo $NAME-$VERSION status:
    echo $STATUS
  else
    echo No such container: $NAME-$VERSION
  fi
}

function start_container {
  echo Starting $NAME-$VERSION
  docker start $NAME-$VERSION
}

function stop_container {
  echo Stoping $NAME-$VERSION
  docker stop $NAME-$VERSION
}

function restart_container {
  echo Restarting $NAME-$VERSION
  docker restart $NAME-$VERSION
}

function list_containers {
  echo -e "Running containers for $NAME\n"
  docker ps -a --filter name=$NAME --format "{{.Names}} ({{.Status}})"
}

function remove_container {
  stop_container
  echo -e "Removing $NAME-$VERSION"
  docker rm $NAME-$VERSION
}

while true ; do
  case "$1" in
    -n|--new)
        NAME=${2:-$NAME}
        OPTION="new"
        shift 2 ;;
    -s|--status)
        NAME=${2:-$NAME}
        OPTION="status"
        shift 2 ;;
    --start)
        NAME=${2:-$NAME}
        OPTION="start"
        shift 2 ;;
    --stop)
        NAME=${2:-$NAME}
        OPTION="stop"
        shift 2 ;;
    -r|--restart)
        NAME=${2:-$NAME}
        OPTION="restart"
        shift 2 ;;
     --remove)
        NAME=${2:-$NAME}
        OPTION="remove"
        shift 2 ;;
    -l|--list)
        NAME=${2:-$NAME}
        OPTION="list"
        shift 2 ;;
    -c|--config)
        [ ! -r $2 -o ! -f $2 ] && ( echo "You must specify a FILE with READ permissions"; exit 1 )
        FILE=${2:-$FILE}
        shift 2 ;;
    -p|--port)
        [[ ! $2 =~ ^[0-9]+$ ]] && ( echo "You must specify a number"; exit 1)
        PORT=${2:-$PORT}
        shift 2
        ;;
    -v|--version)
        VERSION=${2:-$VERSION}
        shift 2 ;;
    -h|--help)
        show_help
        shift ;;
    --) shift ; break ;;
    *) echo "Internal error!" ; exit 1 ;;
  esac
done

case $OPTION in
  new)
    [ -z "$(type -t new_container)" ] && ( echo "You need to define new_container"; exit 1 )
    IMAGE_NAME="$DOCKERNAME:$VERSION"
    NAME_DEFAULT="$NAME-$VERSION"
    PORTS_DEFAULT="$PORT:$STANDAR_PORT"
    RESTART_POLICY_DEFAULT="--restart=unless-stopped"
    DEFAULT_OPTIONS="--name $NAME_DEFAULT -d $RESTART_POLICY_DEFAULT -p $PORTS_DEFAULT"
    echo $NAME-$VERSION in $PORT
    new_container ;;
  status)
    status_container ;;
  start)
    start_container ;;
  stop)
    stop_container ;;
  restart)
    restart_container ;;
  remove)
    stop_container
    remove_container ;;
  list)
    list_containers ;;
esac
